[project]
name = "multi-agentic-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pdfplumber>=0.11.6",
    "pydantic-ai>=0.1.10",
    "pypdf2>=3.0.1",
    "streamlit>=1.45.0",
    "supabase>=2.15.1",
]
